### BASE URL
@baseUrl = http://localhost:3036


### REGISTER USER
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Test1",
  "email": "test1@test.com",
  "password": "123456"
}


### LOGIN (SETS REFRESH TOKEN COOKIE)
### ===============================
# Copy accessToken from response and paste below
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123456"
}


### ===============================
### SET ACCESS TOKEN (MANUAL)
### ===============================
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2Nzc4NzU3MSwiZXhwIjoxNzY3Nzg3NjMxfQ.NxSAqjV29hr1dgr1Jim10y4JSeYCA2EyiGcXXt-qP5hU45s8eNmoSfOhz5_fsXGF7jZuVfQRwdOd_EegHk-5N7UygfLcubUy_SYs7K0AUXXB8FMgPofJgUeFqcYVUZRY9mjcXLaT_sF8akwP8szaodqhaOeaXkcxWs6tdevtPxlxUsEs7dRp9R58taupGUHJ8rn19m8EpE-kxO-gLwVCMTE7ClPDWW8MH8-in0qOSKxXSyEV97AtrG5SlRtykgdK_cluLNMxtvGLomDHiS6Gupx8cfB8evTiAOp5FSjKrqGR32bbHtrEzh-eFOIae_i4Ai8D68AgOfvdefo1HG6wMQ


### GET ALL TODOS (VERIFY ACCESS TOKEN)
### ===============================
GET {{baseUrl}}/todos
Authorization: Bearer {{accessToken}}
### ===============================
### CREATE TODO
### ===============================
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "get"
}


### ===============================
### GET TODO BY ID
### ===============================
GET {{baseUrl}}/todos/1
Authorization: Bearer {{accessToken}}


### ===============================
### UPDATE TODO
### ===============================
PUT {{baseUrl}}/todos/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "update"
}


### ===============================
### DELETE TODO
### ===============================
DELETE {{baseUrl}}/todos/1
Authorization: Bearer {{accessToken}}


### ===============================
### REFRESH ACCESS TOKEN (USES COOKIE)
### ===============================
# No headers
# No body
POST {{baseUrl}}/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2Nzk0MTM5MiwiZXhwIjoxNzY3OTQxODEyfQ.prxe-pO-c8TvVPWsmsKrZhEU5sIwGVgdBNmfjqVVMEqWIz_onai5Fh4o87JyRB3GosTfDPwmtIJriEPVRqcjcGAIlQ0bqW3-92BTcc2_brGJJJAFiMC-ESiFg_5v4A91hjZ9gFJxMp5zMG7Du-9-KIPNXn6RptHd4JHdLDSE-FxBCDKDf7OhAfjWaz323t578Yuab4xYamMMmVN9-xGYV9QSpVSRMZ4CfAJ0EikWgpLhLtIiQoJy86Zz8JgcyfybsBEn0Rog_oikairFDWZIKdccnajUEUtotuFt5pcuJvFxvpo2eq2881WCApdwdIsEST48qm9fnZM5zMH73Rg8GQ

### ===============================
### LOGOUT (INVALIDATES REFRESH TOKEN)
### ===============================
POST {{baseUrl}}/api/auth/logout



































# ### Base URL
# @baseUrl = http://localhost:3036

# ### REGISTER USER
# POST {{baseUrl}}/api/auth/register
# Content-Type: application/json

# {
#   "name": "Test1",
#   "email": "test1@test.com",
#   "password": "123456"
# }

# ### LOGIN (use the same email you registered)
# POST {{baseUrl}}/api/auth/login
# Content-Type: application/json

# {
#   "email": "test1@test.com",
#   "password": "123456"
# }


# ### Get all todos
# GET {{baseUrl}}/todos
# Content-Type: application/json


# ### Get todo by ID
# GET {{baseUrl}}/todos/1
# Content-Type: application/json


# ### Create a new todo
# POST {{baseUrl}}/todos
# Content-Type: application/json

# {
#   "title": "get"
# }


# ### Update an existing todo
# PUT {{baseUrl}}/todos/1
# Content-Type: application/json

# {
#   "title": "update"
# }


# ### Delete a todo
# DELETE {{baseUrl}}/todos/1
# Content-Type: application/json
