### BASE URL
@baseUrl = http://localhost:3036


### REGISTER USER
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Test1",
  "email": "test1@test.com",
  "password": "123456"
}


### LOGIN (SETS REFRESH TOKEN COOKIE)
### ===============================
# Copy accessToken from response and paste below
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123456"
}


### ===============================
### SET ACCESS TOKEN (MANUAL)
### ===============================
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2Nzc4NzU3MSwiZXhwIjoxNzY3Nzg3NjMxfQ.NxSAqjV29hr1dgr1Jim10y4JSeYCA2EyiGcXXt-qP5hU45s8eNmoSfOhz5_fsXGF7jZuVfQRwdOd_EegHk-5N7UygfLcubUy_SYs7K0AUXXB8FMgPofJgUeFqcYVUZRY9mjcXLaT_sF8akwP8szaodqhaOeaXkcxWs6tdevtPxlxUsEs7dRp9R58taupGUHJ8rn19m8EpE-kxO-gLwVCMTE7ClPDWW8MH8-in0qOSKxXSyEV97AtrG5SlRtykgdK_cluLNMxtvGLomDHiS6Gupx8cfB8evTiAOp5FSjKrqGR32bbHtrEzh-eFOIae_i4Ai8D68AgOfvdefo1HG6wMQ


### GET ALL TODOS (VERIFY ACCESS TOKEN)
### ===============================
GET {{baseUrl}}/todos
Authorization: Bearer {{accessToken}}
### ===============================
### CREATE TODO
### ===============================
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "get"
}


### ===============================
### GET TODO BY ID
### ===============================
GET {{baseUrl}}/todos/1
Authorization: Bearer {{accessToken}}


### ===============================
### UPDATE TODO
### ===============================
PUT {{baseUrl}}/todos/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "update"
}


### ===============================
### DELETE TODO
### ===============================
DELETE {{baseUrl}}/todos/1
Authorization: Bearer {{accessToken}}


### ===============================
### REFRESH ACCESS TOKEN (USES COOKIE)
### ===============================
# No headers
# No body
POST {{baseUrl}}/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2Nzc4NzAzNywiZXhwIjoxNzY3Nzg3NDU3fQ.IEOsOdn_I2TRE2AXR2Kry-R-36mg3w8m95z31EeOL_4rsbeQWqefwZIF38aah5-up1EFAjoVApUm7ZeeXY8cNIyKc0pisjnd_sJgLw3vl5DhnKd4uBTSB9nDLg9CPdp2L6JkQYADBkzCzffXnHLi6CkFtgj4QBcpI_5f1SHI6Tsr6sM8AJdCOaloFFVJfIoOVDWaxlneskI0j6TVD0o00Rjh5g2XzJ7BZbHXhGEX78VHWxIzij2S4nEZFNO2znJwEMsmypGqJ__kjBy9sPtV376EVHoJSNEi9dARrAgjteCCLF4Oe3W9fMpOTLzlyBMwEMIlX_RYgnHKjQHPbOrV-w

### ===============================
### LOGOUT (INVALIDATES REFRESH TOKEN)
### ===============================
POST {{baseUrl}}/api/auth/logout



































# ### Base URL
# @baseUrl = http://localhost:3036

# ### REGISTER USER
# POST {{baseUrl}}/api/auth/register
# Content-Type: application/json

# {
#   "name": "Test1",
#   "email": "test1@test.com",
#   "password": "123456"
# }

# ### LOGIN (use the same email you registered)
# POST {{baseUrl}}/api/auth/login
# Content-Type: application/json

# {
#   "email": "test1@test.com",
#   "password": "123456"
# }


# ### Get all todos
# GET {{baseUrl}}/todos
# Content-Type: application/json


# ### Get todo by ID
# GET {{baseUrl}}/todos/1
# Content-Type: application/json


# ### Create a new todo
# POST {{baseUrl}}/todos
# Content-Type: application/json

# {
#   "title": "get"
# }


# ### Update an existing todo
# PUT {{baseUrl}}/todos/1
# Content-Type: application/json

# {
#   "title": "update"
# }


# ### Delete a todo
# DELETE {{baseUrl}}/todos/1
# Content-Type: application/json
